'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default1

	'''<summary>
	'''IssuesCtl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents IssuesCtl As Global.System.Web.UI.WebControls.Repeater

	'''<summary>
	'''TitlesCtl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TitlesCtl As Global.System.Web.UI.WebControls.Repeater

	'''<summary>
	'''TitleCtl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TitleCtl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
